remote_theme: rms-open-letter/minima
languages:
  - name: "Brazilian Portuguese"
    code: "pt"
  - name: "French"
    code: "fr"
  - name: "German"
    code: "de"
  - name: "Italian"
    code: "it"
  - name: "Polish"
    code: "pl"
  - name: "Spanish"
    code: "es"
  - name: "Turkish"
    code: "tr"
