remote_theme: rms-open-letter/minima
languages:
  - name: "Arabic"
    code: "ar"
  - name: "Brazilian Portuguese"
    code: "pt"
  - name: "Dutch"
    code: "nl"
  - name: "French"
    code: "fr"
  - name: "Galician"
    code: "ga"
  - name: "German"
    code: "de"
  - name: "Italian"
    code: "it"
  - name: "Japanese"
    code: "ja"
  - name: "Korean"
    code: "ko"
  - name: "Persian"
    code: "fa"
  - name: "Polish"
    code: "pl"
  - name: "Simplified Chinese"
    code: "zh_CN"
  - name: "Spanish"
    code: "es"
  - name: "Traditional Chinese"
    code: "zh_TW"
  - name: "Turkish"
    code: "tr"
  - name: "Russian"
    code: "ru"
